### ISSUE TITLE
Add Logout functionality

### ISSUE THREAD

**Issue by gotpredictions** [svpmtrust/autotest#51]

**Comment by BabyManisha** [comment]
done

**Comment by gotpredictions** [comment]
Is this merged into github?

On Fri, Jan 16, 2015 at 6:30 PM, Baby Manisha.Sunkara <
notifications@github.com> wrote:

> Closed #51 <https://github.com/svpmtrust/autotest/issues/51>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/svpmtrust/autotest/issues/51#event-220448170>.
>



-- 
Eswar Vandanapu (ఈశ్వర్ వందనపు)
Platform Architect
General Manager - Indian Operations
Aviso, Inc
